version: 2
updates:
  - package-ecosystem: npm
    directory: /
    versioning-strategy: increase-if-necessary
    schedule:
      interval: daily
    groups:
      typescript-eslint:
        patterns:
          - '@typescript-eslint/*'
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
