version: 2
jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-v1-{{ checksum "./yarn.lock" }}-{{ .Branch }}
            - yarn-v1-{{ checksum "./yarn.lock" }}-master
            - yarn-v1-{{ checksum "./yarn.lock" }}-
            - yarn-v1-
      - run:
          name: Install packages
          command: yarn --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache:
          key: yarn-v1-{{ checksum "./yarn.lock" }}-{{ .Branch }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Check code formatting
          command: yarn run prettier:check
          when: always
      - run:
          name: Check prettier conflicts
          command: yarn run lint:check-prettier-conflicts
          when: always
      - run:
          name: Lint
          command: yarn run lint
          when: always
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  release:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Release
          command: yarn run release
workflows:
  version: 2
  workflow:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: master
