name: cd
on:
  push:
    branches:
      - '**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  latest:
    if: github.ref_name == github.event.repository.default_branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}
      - id: git-cliff
        uses: orhun/git-cliff-action@v4
        with:
          args: --bump
      - name: push tag
        run: |
          if git tag "${{ steps.git-cliff.outputs.version }}" 2>/dev/null; then
            git push origin --tags
          else
            echo "No relevant changes to publish"
          fi
