name: cd
on:
  push:
    branches:
      - '**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  latest:
    if: github.ref_name == github.event.repository.default_branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-tags: true
          token: ${{ secrets.GH_PAT }}
      - name: push tag
        run: |
          if git tag "v$(jq -r '.version' package.json)" 2>/dev/null; then
            git push origin --tags
          else
            echo "No relevant changes to publish"
          fi
