name: cd
on:
  push:
    branches:
      - master
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - id: git-cliff
        uses: orhun/git-cliff-action@v4
        with:
          args: --bump
      - name: bump version
        run: |
          if git tag "${{ steps.git-cliff.outputs.version }}" 2>/dev/null; then
            git push origin --tags
          else
            echo "No relevant changes to publish"
          fi
