name: create-release
on:
  push:
    tags:
      - v[0-9]+\.[0-9]+\.[0-9]+
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - id: git-cliff
        uses: orhun/git-cliff-action@v4
        with:
          args: --current --strip all
      - uses: softprops/action-gh-release@v2
        with:
          body_path: ${{ steps.git-cliff.outputs.changelog }}
          token: ${{ secrets.GH_PAT }}
