name: pull-request
on:
  - pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint-commit-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - uses: asdf-vm/actions/install@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
        with:
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm exec commitlint --verbose --from="remotes/origin/$GITHUB_BASE_REF"
