name: release-notes
on:
  push:
    tags:
      - v[0-9]+\.[0-9]+\.[0-9]+
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - uses: asdf-vm/actions/install@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
        with:
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - name: generate release notes
        id: release-notes
        run: |
          echo "content<<EOF" >>$GITHUB_OUTPUT
          pnpm exec git-cliff --latest --strip all >>$GITHUB_OUTPUT
          echo "EOF" >>$GITHUB_OUTPUT
      - uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.release-notes.outputs.content }}
